#!/bin/sh
​
FORBIDDEN_HTTPS_URL="https://github.com/gabia/git-hooks-study.git" 
FORBIDDEN_SSH_URL="git@github.com:gabia/git-hooks-study.git" 
FORBIDDEN_REF="refs/heads/main" 
​
ARR_GIT_PARAMS=($(echo $HUSKY_GIT_PARAMS))
ARR_GIT_STDIN=($(echo $HUSKY_GIT_STDIN))
​
remote=${ARR_GIT_PARAMS[0]}
url=${ARR_GIT_PARAMS[1]}
​
local_ref=${ARR_GIT_STDIN[0]}
local_sha=${ARR_GIT_STDIN[1]}
remote_ref=${ARR_GIT_STDIN[2]}
remote_sha=${ARR_GIT_STDIN[3]}
​
if [ "$url" != "$FORBIDDEN_HTTPS_URL" -a "$url" != "$FORBIDDEN_SSH_URL" ]
then
    exit 0 
fi
​
if [ "$remote_ref" == "$FORBIDDEN_REF" ]
then
    echo "DO NOT PUSH it master"
    exit 1
fi
​
exit 0